### ISSUE TITLE
Documentation failed to build

### ISSUE THREAD

**Issue by maxsch3** [maxsch3/keras-batchflow#105]
Error log

```
3.32s$ mkdocs build --verbose --clean --strict
DEBUG   -  Loading configuration file: /home/travis/build/maxsch3/keras-batchflow/mkdocs.yml 
DEBUG   -  Loaded theme configuration for 'readthedocs' from '/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/mkdocs/themes/readthedocs/mkdocs_theme.yml': {'static_templates': ['404.html'], 'include_search_page': True, 'search_index_only': False, 'highlightjs': True, 'hljs_languages': []} 
DEBUG   -  Config value: 'config_file_path' = '/home/travis/build/maxsch3/keras-batchflow/mkdocs.yml' 
DEBUG   -  Config value: 'site_name' = 'Keras batchflow' 
DEBUG   -  Config value: 'nav' = [{'Home': 'index.md'}, {'User guide': 'user_guide.md'}, {'Examples': [{'basic usage': 'titanic_example.ipynb'}]}, {'API': [{'Batch generators': 'batch_generators_api.md'}, {'Batch transformers': 'batch_transformers_api.md'}]}] 
DEBUG   -  Config value: 'pages' = None 
DEBUG   -  Config value: 'site_url' = '' 
DEBUG   -  Config value: 'site_description' = None 
DEBUG   -  Config value: 'site_author' = None 
DEBUG   -  Config value: 'theme' = Theme(name='readthedocs', dirs=['/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/mkdocs/themes/readthedocs', '/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/mkdocs/templates'], static_templates=['sitemap.xml', '404.html'], include_search_page=True, search_index_only=False, highlightjs=True, hljs_languages=[]) 
DEBUG   -  Config value: 'docs_dir' = '/home/travis/build/maxsch3/keras-batchflow/docs' 
DEBUG   -  Config value: 'site_dir' = '/home/travis/build/maxsch3/keras-batchflow/site' 
DEBUG   -  Config value: 'copyright' = None 
DEBUG   -  Config value: 'google_analytics' = None 
DEBUG   -  Config value: 'dev_addr' = Address(host='127.0.0.1', port=8000) 
DEBUG   -  Config value: 'use_directory_urls' = True 
DEBUG   -  Config value: 'repo_url' = 'https://github.com/maxsch3/keras-batchflow/' 
DEBUG   -  Config value: 'repo_name' = 'GitHub' 
DEBUG   -  Config value: 'edit_uri' = 'edit/master/docs/' 
DEBUG   -  Config value: 'extra_css' = ['css/custom.css'] 
DEBUG   -  Config value: 'extra_javascript' = ['https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'] 
DEBUG   -  Config value: 'extra_templates' = [] 
DEBUG   -  Config value: 'markdown_extensions' = ['toc', 'tables', 'fenced_code', 'admonition', 'codehilite', 'mkautodoc', 'pymdownx.arithmatex'] 
DEBUG   -  Config value: 'mdx_configs' = {} 
DEBUG   -  Config value: 'strict' = True 
DEBUG   -  Config value: 'remote_branch' = 'gh-pages' 
DEBUG   -  Config value: 'remote_name' = 'origin' 
DEBUG   -  Config value: 'extra' = {} 
DEBUG   -  Config value: 'plugins' = PluginCollection([('mkdocs-jupyter', <mkdocs_jupyter.plugin.Plugin object at 0x7fc34f7290b8>)]) 
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/travis/build/maxsch3/keras-batchflow/site 
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - examples.md 
DEBUG   -  Reading markdown pages. 
ERROR   -  Error reading page 'titanic_example.ipynb': markdown.tpl 
Converting: /home/travis/build/maxsch3/keras-batchflow/docs/titanic_example.ipynb
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/mkdocs/__main__.py", line 163, in build_command
    ), dirty=not clean)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/mkdocs/commands/build.py", line 274, in build
    _populate_page(file.page, config, files, dirty)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/mkdocs/commands/build.py", line 177, in _populate_page
    page.render(config, files)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/mkdocs_jupyter/plugin.py", line 57, in new_render
    self.toc = get_nb_toc(page.file.abs_src_path)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/mkdocs_jupyter/plugin.py", line 67, in get_nb_toc
    body = convert.nb2md(fpath)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/mkdocs_jupyter/convert.py", line 103, in nb2md
    body, resources = exporter.from_filename(nb_path)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/nbconvert/exporters/templateexporter.py", line 387, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/mkdocs_jupyter/assets/md-no-codecell.tpl", line 1, in top-level template code
    {% extends 'markdown.tpl'%}
jinja2.exceptions.TemplateNotFound: markdown.tpl
The command "mkdocs build --verbose --clean --strict" failed and exited with 1 during .
Your build has been stopped.
```

I have found a solution here:
https://github.com/danielfrg/mkdocs-jupyter/issues/16

I need to roll back version of nbconvert to nbconvert==5.6.1

Solution: 
add the above line to build_requirements.txt

**Comment by maxsch3** [comment]
Fixed
